services:
  django-web:
    build: .
    container_name: django-docker
    ports:
      - "8000:8000"
    env_file:
      - .env
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"